// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./src/views/Layout/AdminLayout.vue')['default']
    App: typeof import('./src/App.vue')['default']
    BaseFormLoginAndRegister: typeof import('./src/components/GobalLayout/BaseFormLoginAndRegister.vue')['default']
    BreadcrumbHeader: typeof import('./src/components/GobalLayout/BreadcrumbHeader.vue')['default']
    Company: typeof import('./src/views/Pages/Company/Company.vue')['default']
    CompanyTable: typeof import('./src/views/Pages/Company/TabItem/CompanyTable.vue')['default']
    DefaultLayout: typeof import('./src/views/Layout/DefaultLayout.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Index: typeof import('./src/views/Pages/Company/Index.vue')['default']
    Login: typeof import('./src/views/Pages/Login.vue')['default']
    LoginForm: typeof import('./src/views/Pages/Register/LoginForm.vue')['default']
    Manage: typeof import('./src/views/Pages/Company/TabItem/Manage.vue')['default']
    RegisterForm: typeof import('./src/views/Pages/Register/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableActionMenu: typeof import('./src/components/GobalLayout/TableActionMenu.vue')['default']
    TabTestTable: typeof import('./src/views/Pages/Test/TabItems/TabTestTable.vue')['default']
    Test: typeof import('./src/views/Pages/Test/test.vue')['default']
    TheMenu: typeof import('./src/components/GobalLayout/TheMenu.vue')['default']
    Undefined: typeof import('./src/views/Pages/Test/index.vue')['default']
    UploadImage: typeof import('./src/components/GobalLayout/UploadImage.vue')['default']
  }
}
